# Generated by Django 2.2.4 on 2020-12-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_me', '0002_auto_20201223_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rate_me.user_roles'),
        ),
    ]
