# Generated by Django 2.2.4 on 2020-12-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_me', '0004_auto_20201223_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_type',
            old_name='commpany',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comfort',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='durable',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fuel',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='safety',
            field=models.FloatField(null=True),
        ),
    ]
