# Generated by Django 2.2.4 on 2020-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_me', '0006_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_type',
            name='avg',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='car_type',
            name='nor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comfort',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='durable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fuel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='safety',
            field=models.IntegerField(null=True),
        ),
    ]
