# Generated by Django 2.2.4 on 2020-12-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_me', '0007_auto_20201226_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_type',
            name='avg',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, null=True),
        ),
    ]
